## NumPy

NumPy is a python package designed for scientific computing. NumPy gives python many of the same tools available in MATLAB. The NumPy array object is very powerful. NumPy is related to SciPy which we will try later. 

Please find further documentation on NumPy here: https://docs.scipy.org/doc/

If you are a MATLAB user the following table could be helpful for learning NumPy:
https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html

## numpy arrays

In [1]:
from numpy import zeros
a = zeros(4,float)
print(a)

[ 0.  0.  0.  0.]


In [2]:
a = zeros([3,4],float)
print(a)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [3]:
from numpy import ones
a = ones(6,float)
print(a)

[ 1.  1.  1.  1.  1.  1.]


In [4]:
from numpy import empty
a = empty(5,float) 
print(a)

[ 0.  0.  0.  0.  0.]


Convert a list to an array

In [5]:
from numpy import array
r = [ 1.0, 1.5, -2.2]
a = array(r,float)
print(a)

[ 1.   1.5 -2.2]


Elements of an array

In [6]:
from numpy import array
r = [ 1.0, 1.5, -2.2]
a = array(r,float)
print(a)
print(a[0])
print(a[2])

[ 1.   1.5 -2.2]
1.0
-2.2


Make a 2-d array by combining lists (list of lists)

In [7]:
a = array([[1,2,3],[4,5,6]],int)
print(a)

[[1 2 3]
 [4 5 6]]


Create a 2-d array

In [8]:
from numpy import zeros
a = zeros([2,2],int)
a[0,1]=1
a[1,0]=-1
print(a)

[[ 0  1]
 [-1  0]]


Create a Arithmetic with arrays

In [9]:
from numpy import array
a = array([1,2,3,4],int)
b = 2*a
print(b)
print(a+b)
print(b+1)

[2 4 6 8]
[ 3  6  9 12]
[3 5 7 9]


Multiplication is also element by element - it is not the dot product. There is a special function for that:

In [10]:
print(a)
print(b)
print(a*b)

[1 2 3 4]
[2 4 6 8]
[ 2  8 18 32]


In [11]:
from numpy import array,dot
a = array([1,2,3,4],int)
b = array([2,4,6,8],int)
print(dot(a,b))

60


2D arrays are similar. Multiplication is element by element. If you want to calculate the matrix product use dot

In [12]:
a=array([[0,1],[-1,0]],int)
print(a)

[[ 0  1]
 [-1  0]]


In [13]:
b=array([[2,4],[0,1]],int)
print(b)

[[2 4]
 [0 1]]


In [14]:
print(a*b)

[[0 4]
 [0 0]]


In [15]:
print(dot(a,b))

[[ 0  1]
 [-2 -4]]


In [16]:
c=[10,2]
print(dot(a,c))

[  2 -10]


Built in functions acting on arrays

In [18]:
r = [ 1.0, 4, 2.2]
a = array(r,float)
print(a)

[ 1.   4.   2.2]


In [19]:
sum(a)

7.2000000000000002

In [20]:
len(a)

3

In [21]:
max(a)

4.0

In [22]:
from math import sqrt
b=array(list(map(sqrt,a)),float)
print(b)

[ 1.         2.         1.4832397]


Functions for 2-d arrays

In [23]:
a=array([[1,2,3],[4,5,6]],int)
print(a)

[[1 2 3]
 [4 5 6]]


In [24]:
print(a.size)  # total number of elements
print(a.shape) # number of dimensions along each axis

6
(2, 3)


#### Array basics

In [25]:
import numpy as np

In [26]:
data = np.array([[1,2],[3,4],[5,6]])

In [27]:
type(data)

numpy.ndarray

In [28]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
data.ndim

2

In [30]:
data.shape

(3, 2)

In [31]:
data.size

6

In [32]:
data.dtype

dtype('int64')

In [33]:
data.nbytes

48

#### Indexing and Slicing

In [34]:
# arange creates a numpy array consiting of evenly spaced values within an interval 
# arange([start, ]stop, [step, ]dtype=None)
a = np.arange(0,11)  

In [35]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
a[0] # the first element (index 0)

0

In [37]:
a[-1] # the last element (index -1)

10

In [38]:
a[4] # index 4

4

##### Slicing

In [39]:
# Select the elements of an array 
# i:j:k where i is the starting index, j is the stopping index, and k is the step
a[2:] #select all elements of the array after index 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
a[:-1] #select all elements of the array except for the last element

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a[1:-1] # 2nd element (index 1) to 2nd to last element index (index -1 is not included)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a[0:] # the whole array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
a[:] # the whole array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
a[0::2] # every other element starting with index 0

array([ 0,  2,  4,  6,  8, 10])

In [45]:
a[1::2] # every other element starting with index 1

array([1, 3, 5, 7, 9])

In [46]:
a[:5]  # the first five elements (index 0 to 4)

array([0, 1, 2, 3, 4])

In [47]:
a[-5:] # the last five elements of the arrah

array([ 6,  7,  8,  9, 10])

In [48]:
a[-2:]

array([ 9, 10])

In [23]:
a[::-1] # reverse the array

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [24]:
a[::-2] # reverse the array selecting every 2nd value

array([10,  8,  6,  4,  2,  0])

##### Multidimensional array slicing

In [49]:
A = np.array([[ 0,  1,  2,  3,  4,  5],
              [10, 11, 12, 13, 14, 15],
              [20, 21, 22, 23, 24, 25],
              [30, 31, 32, 33, 34, 35],
              [40, 41, 42, 43, 44, 45],
              [50, 51, 52, 53, 54, 55]])

In [31]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [32]:
A[:,0] # The 1st column   # [row, column] # [all rows, column 0]

array([ 0, 10, 20, 30, 40, 50])

In [33]:
A[:,1] # The 2nd column

array([ 1, 11, 21, 31, 41, 51])

In [34]:
A[0:3,1] # The first 3 rows of the 2nd column

array([ 1, 11, 21])

In [35]:
A[2,:] # The third row

array([20, 21, 22, 23, 24, 25])

In [36]:
A[:3,:3] # subarray - top left # [row 1-3, column 1-3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [37]:
A[3:,:3] # subarray - bottomleft # [row 4-end, column 0-3]

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [38]:
A[::2, ::2] # subarray - every second element starting from index 0-0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [39]:
A[1::2,1::3] # every second row starting with index 1, every third column starting with

array([[11, 14],
       [31, 34],
       [51, 54]])