# Notebook 16 - Solving Linear Equations

Example 1: Find $x$, $y$ given:

$2x+3y=8$

$8x-2y=4$

Example 2 (from the book): Find $w$, $x$, $y$, $z$ given:

$2w+x+4y+z=-4$

$3w+4x-y-z=3$

$w-4x+y+5z=9$

$2w-2x+y+3z=7$

### Gaussian Elimination with Backsubstitution

Goal: solve Ax=v, where A is NxN

In [1]:
# Gaussian elimination with backsubstitution
# Modified book Example 6.1

from numpy import array,empty,zeros

# Define A and v which satisfy Ax=v where x is a vector with N elements

# NxN array


# Example 1
A = array([[ 2,   3 ],
           [ 8,  -2 ]], float)
# 1D array with N elements
v = array([ 8,4],float)

"""

# Example 2 ( from the book):

A = array([[ 2,  1,  4,  1 ],
           [ 3,  4, -1, -1 ],
           [ 1, -4,  1,  5 ],
           [ 2, -2,  1,  3 ]], float)
v = array([ -4, 3, 9, 7 ],float)
"""

# N equations and N unknowns
N = len(v)
print("N=",N)

print("-------------")
print("Before GE")
print("Matrix =")
print(A)
print("Vector =")
print(v)
print("-------------")

# Choose if you want to print a lot:
verbose = True

# Gaussian elimination

#  For each row of A
for m in range(N):


    if verbose:
      print("Considering matrix row",m," of ",N)


    # Find the diagonal element of that row
    div = A[m,m]

    if verbose:
      print(" Diagonal element = ",div)

    # Divide every column of row m by that diagonal (apply also to v)
    A[m,:] /= div
    v[m] /= div

    if verbose:
      print(" Matrix after dividing by diagonal element for row ",m,"= ")
      print(A)
      print(" Vector after dividing by diagonal element for row ",m,"= ")
      print(v)

    # For each row under row m, subtract a multiple of row m such that mth column becomes zero

    #  Consider row i, where i is greater than m
    if verbose:
      print( "Loop over ever row i, where i is greater than our current row ",m)
    for i in range(m+1,N):

      # Get the multiplier (the value of row i column m)
      mult = A[i,m]

      if verbose:
        print("  Row",i, "multiplier",mult, " (the value or row ",i, "column", m,")")
        print("  Use numpy to change multiple columns in this row simultaneously")
        print("     Row ",i," -",mult,"* Row",m)

      # For each column in row i, subtract mult times the value of that column entry in row m (apply also to v)
      A[i,:] -= mult*A[m,:]
      v[i] -= mult*v[m]

      if verbose:
        print(" Matrix after subtract mult times the value of that column entry in row m = ")
        print(A)
        print(" Vector after subtract mult times the value of that column entry in row m = ")
        print(v)


# Print array after gaussian substititution
print("-------------")
print("After GE")
print("Matrix =")
print(A)
print("Vector =")
print(v)
print("-------------")

# Backsubstitution
x = zeros(N,float)

print("Start Backsubstitution (find x given Ax=v)")
print("-------------")
#  Start with the last row and step backwards
if verbose:
  print("   We already know the last row x[-1] =",v[N-1])
  print("   Use this to work backwards and find each x value for each row")
  print("   x is currently blank:",x)
for m in range(N-1,-1,-1):

    # Get the v value
    x[m] = v[m]

    if verbose:
      print("     Row ",m," ---> Assign initial x[",m,"] = vector component =",v[m])

    # First time through this loop is not entered.
    # In following m loops, we subtract each column entry of that row from the v value
    #  starting with the element to the right of the diagonal element
    for i in range(m+1,N):
        if verbose:
          print("      x[",m,"] before change =",x[m])
          print("      x[",m,"] = ", x[m] ,"- A[",m,",",i,"] * x[",i,"]" )
          print("               = ", x[m], " - ", A[m,i],"*", x[i] )
          print("               = ", x[m]  -  A[m,i]* x[i] )
        x[m] -= A[m,i]*x[i]
        if verbose:
          print("      x[",m,"] after change =",x[m])


print("-------------")
print("\nfinal result:")
print(x)

N= 2
-------------
Before GE
Matrix =
[[ 2.  3.]
 [ 8. -2.]]
Vector =
[8. 4.]
-------------
Considering matrix row 0  of  2
 Diagonal element =  2.0
 Matrix after dividing by diagonal element for row  0 = 
[[ 1.   1.5]
 [ 8.  -2. ]]
 Vector after dividing by diagonal element for row  0 = 
[4. 4.]
Loop over ever row i, where i is greater than our current row  0
  Row 1 multiplier 8.0  (the value or row  1 column 0 )
  Use numpy to change multiple columns in this row simultaneously
     Row  1  - 8.0 * Row 0
 Matrix after subtract mult times the value of that column entry in row m = 
[[  1.    1.5]
 [  0.  -14. ]]
 Vector after subtract mult times the value of that column entry in row m = 
[  4. -28.]
Considering matrix row 1  of  2
 Diagonal element =  -14.0
 Matrix after dividing by diagonal element for row  1 = 
[[ 1.   1.5]
 [-0.   1. ]]
 Vector after dividing by diagonal element for row  1 = 
[4. 2.]
Loop over ever row i, where i is greater than our current row  1
-------------
Afte

Note the "signed zeros"

Note also: Gaussian Elimination (GE) results in an "upper triangular" matrix, aka "echelon" form.

One can manipulate the matrix further (Gauss-Jordon elimination) to produce "reduced row echelon form"
but this is typically not done computationally...it requires ~50% more computation time than the method above.


We also run into an issue when the upper left element of the matrix is a zero:

In [2]:
# Gaussian elimination with backsubstitution
# Modified book Example 6.1

from numpy import array,empty

# Define A and v which satisfy Ax=v where x is a vector with N elements

# NOTE: MODIFIED MATRIX A W.R.T. PREVIOUS EXAMPLE

# NxN array
A = array([[ 0,   3 ],
           [ 8,  -2 ]], float)
# 1D array with N elements
v = array([ 8,4],float)


# For reference:
# Example from the book:

#A = array([[ 2,  1,  4,  1 ],
#           [ 3,  4, -1, -1 ],
#           [ 1, -4,  1,  5 ],
#           [ 2, -2,  1,  3 ]], float)
#v = array([ -4, 3, 9, 7 ],float)


# N equations and N unknowns
N = len(v)
print("N=",N)

print("Before GE")
print(A)

# Gaussian elimination

#  For each row of A
for m in range(N):

    # Find the diagonal element of that row
    div = A[m,m]

    # Divide every column of row m by that diagonal (apply also to v)
    A[m,:] /= div
    v[m] /= div

    # For each row under row m, subtract a multiple of row m such that mth column becomes zero

    #  Consider row i, where i is greater than m
    for i in range(m+1,N):
        # Get the multiplier (the value of row i column m)
        mult = A[i,m]
        # For each column in row i, subtract mult times the value of that column entry in row m (apply also to v)
        A[i,:] -= mult*A[m,:]
        v[i] -= mult*v[m]

# Print array after gaussian substititution
print("After GE")
print(A)

# Backsubstitution
x = empty(N,float)

#  Start with the last row and step backwards
for m in range(N-1,-1,-1):

    # Get the v value
    x[m] = v[m]

    # First time through this loop is not entered.
    # In following m loops, we subtract each column entry of that row from the v value
    #  starting with the element to the right of the diagonal element
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]

print("\nfinal result:")
print(x)

N= 2
Before GE
[[ 0.  3.]
 [ 8. -2.]]
After GE
[[nan inf]
 [nan nan]]

final result:
[nan nan]


<ipython-input-2-0c53175dcca8>:43: RuntimeWarning: divide by zero encountered in divide
  A[m,:] /= div
<ipython-input-2-0c53175dcca8>:43: RuntimeWarning: invalid value encountered in divide
  A[m,:] /= div
<ipython-input-2-0c53175dcca8>:44: RuntimeWarning: divide by zero encountered in double_scalars
  v[m] /= div
<ipython-input-2-0c53175dcca8>:44: RuntimeWarning: invalid value encountered in double_scalars
  v[m] /= div


What do we do if the first element of our matrix is zero? This breaks GE.

### Pivotting

Standard method of dealing with solving equations where element 0,0 is =0

In [3]:
# Gaussian elimination with backsubstitution
# Modified book Example 6.1

from numpy import array,empty

# Define A and v which satisfy Ax=v where x is a vector with N elements


# NOTE: SWAPPED ROWS W.R.T. PREVIOUS EXAMPLE

# NxN array
A = array([[ 8,   -2 ],
           [ 0,   3 ]], float)
# 1D array with N elements
v = array([ 4,8],float)


# For reference:
# Example from the book:

#A = array([[ 2,  1,  4,  1 ],
#           [ 3,  4, -1, -1 ],
#           [ 1, -4,  1,  5 ],
#           [ 2, -2,  1,  3 ]], float)
#v = array([ -4, 3, 9, 7 ],float)


# N equations and N unknowns
N = len(v)
print("N=",N)

print("Before GE")
print(A)

# Gaussian elimination

#  For each row of A
for m in range(N):

    # Find the diagonal element of that row
    div = A[m,m]

    # Divide every column of row m by that diagonal (apply also to v)
    A[m,:] /= div
    v[m] /= div

    # For each row under row m, subtract a multiple of row m such that mth column becomes zero

    #  Consider row i, where i is greater than m
    for i in range(m+1,N):
        # Get the multiplier (the value of row i column m)
        mult = A[i,m]
        # For each column in row i, subtract mult times the value of that column entry in row m (apply also to v)
        A[i,:] -= mult*A[m,:]
        v[i] -= mult*v[m]

# Print array after gaussian substititution
print("After GE")
print(A)

# Backsubstitution
x = empty(N,float)

#  Start with the last row and step backwards
for m in range(N-1,-1,-1):

    # Get the v value
    x[m] = v[m]

    # First time through this loop is not entered.
    # In following m loops, we subtract each column entry of that row from the v value
    #  starting with the element to the right of the diagonal element
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]

print("\nfinal result:")
print(x)

N= 2
Before GE
[[ 8. -2.]
 [ 0.  3.]]
After GE
[[ 1.   -0.25]
 [ 0.    1.  ]]

final result:
[1.16666667 2.66666667]


In this simple example swapping row
s worked to avoid this problem.

This swapping, or "pivotting", has to be done carefully. It is easy to introduce new problems when fixing this one.

The standards technique is "partial pivotting". Standard GE involves subtracting some multiple of the diagonal element for each element of a row for each column. Partial pivotting involves;

* Before moving to a new row, consider swapping that row for a different one (re-arranging rows at each stage)
* If you are starting row m, choose (swap) the row with mth element furthest from zero (positive or negative).

In [4]:
# Gaussian elimination with backsubstitution and pivoting
# Modified book Example 6.1

from numpy import array,empty

# Define A and v which satisfy Ax=v where x is a vector with N elements

# NxN array
#A = array([[ 0,   3 ],
#           [ 8,  -2 ]], float)
# 1D array with N elements
#v = array([ 8,4],float)

A = array([[ 0,  2,  7  ],
           [ 7,  1,  3 ],
           [ 2,  -5, 1 ]], float)

v = array([ -4, 3, 9  ],float)



#A = array([[ 2,  1,  4,  1 ],
#           [ 3,  0,  1,  3 ],
#           [ 3,  4, -1, -1 ],
#           [ 1, -4,  1,  5 ]], float)
#
#v = array([ -4, 3, 9, 7 ],float)


# N equations and N unknowns
N = len(v)
print("N=",N)

print("Before GE")
print(A)

# Gaussian elimination

#  For each row of A
for m in range(N):

    print("\nIteration - row ",m)

    print("Before pivot")
    print(A)

    # Find row with biggest pivot element

    #  save the row number which you which to swap. initialize with the current row
    pivot = m

    #  inititalize "largest" with the diagonal element of the current row.
    largest = A[m,m]

    # for each row after the one you are currently looking at
    for i in range(m+1,N):
        # find the row which has element in column m which is largest
        if abs(A[i,m])>largest:
            largest = abs(A[i,m])
            pivot = i

    # Swap rows
    for i in range(N):
        A[m,i], A[pivot,i] = A[pivot,i], A[m,i]
    v[m],v[pivot] = v[pivot],v[m]

    print("After pivot")
    print(A)

    # Find the diagonal element of that row
    div = A[m,m]

    # Divide every column of row m by that diagonal (apply also to v)
    A[m,:] /= div
    v[m] /= div

    # For each row under row m, subtract a multiple of row m such that mth column becomes zero

    #  Consider row i, where i is greater than m
    for i in range(m+1,N):
        # Get the multiplier (the value of row i column m)
        mult = A[i,m]
        # For each column in row i, subtract mult times the value of that column entry in row m (apply also to v)
        A[i,:] -= mult*A[m,:]
        v[i] -= mult*v[m]

# Print array after gaussian substititution
print("After GE")
print(A)

# Backsubstitution
x = empty(N,float)

#  Start with the last row and step backwards
for m in range(N-1,-1,-1):

    # Get the v value
    x[m] = v[m]

    # First time through this loop is not entered.
    # In following m loops, we subtract each column entry of that row from the v value
    #  starting with the element to the right of the diagonal element
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]

print("\nfinal result:")
print(x)

N= 3
Before GE
[[ 0.  2.  7.]
 [ 7.  1.  3.]
 [ 2. -5.  1.]]

Iteration - row  0
Before pivot
[[ 0.  2.  7.]
 [ 7.  1.  3.]
 [ 2. -5.  1.]]
After pivot
[[ 7.  1.  3.]
 [ 0.  2.  7.]
 [ 2. -5.  1.]]

Iteration - row  1
Before pivot
[[ 1.          0.14285714  0.42857143]
 [ 0.          2.          7.        ]
 [ 0.         -5.28571429  0.14285714]]
After pivot
[[ 1.          0.14285714  0.42857143]
 [ 0.         -5.28571429  0.14285714]
 [ 0.          2.          7.        ]]

Iteration - row  2
Before pivot
[[ 1.          0.14285714  0.42857143]
 [-0.          1.         -0.02702703]
 [ 0.          0.          7.05405405]]
After pivot
[[ 1.          0.14285714  0.42857143]
 [-0.          1.         -0.02702703]
 [ 0.          0.          7.05405405]]
After GE
[[ 1.          0.14285714  0.42857143]
 [-0.          1.         -0.02702703]
 [ 0.          0.          1.        ]]

final result:
[ 0.70498084 -1.5440613  -0.1302682 ]


### Lower Upper (LU) Decomposition

Alternative method for solving a system of equations.

Preferable when A is fixed and you are solving for many v (Ax=v)

In [5]:
# LU Decomposition (no pivoting)
from numpy import zeros, empty, copy, array

#A = array([[ 6,  2,  7  ],
#           [ 7,  1,  3 ],
#           [ 2,  -5, 1 ]], float)

#v = array([ -4, 3, 9  ],float)

A = array([[ 2,  1,  4,  1 ],
           [ 3,  4, -1, -1 ],
           [ 1, -4,  1,  5 ],
           [ 2, -2,  1,  3 ]], float)
v = array([ -4, 3, 9, 7 ],float)

N = len(v)

def LU(A):
    L = zeros([N,N],float)
    U = copy(A)

    for m in range(N):

        # Copy elements into the L matrix
        L[m:N,m] = U[m:N,m]

        #Divide by the diagonal element
        div = U[m,m]
        U[m,:] /=div

        #Subtract from the lower rows
        for i in range(m+1,N):
            mult = U[i,m]
            U[i,:] -= mult*U[m,:]

    return L,U

# main
L, U = LU(A)

print(L)
print(U)

# BS #1
y= empty(N,float)
for m in range(N):
    y[m]=v[m]
    for i in range(m):
        y[m]-=L[m,i]*y[i]
    y[m]/=L[m,m]

# BS #2
x= empty(N,float)
for m in range(N-1,-1,-1):
    y[m]=y[m]
    for i in range(m+1,N):
        x[m]-=U[m,i]*x[i]

print(x)

[[  2.    0.    0.    0. ]
 [  3.    2.5   0.    0. ]
 [  1.   -4.5 -13.6   0. ]
 [  2.   -3.  -11.4  -1. ]]
[[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [-0.  -0.  -0.   1. ]]
[-24.95  21.9    8.    -2.  ]


### Numpy

one can also just let numpy do the work:

In [6]:
from numpy.linalg import solve


A = array([[ 2,  1,  4,  1 ],
           [ 3,  4, -1, -1 ],
           [ 1, -4,  1,  5 ],
           [ 2, -2,  1,  3 ]], float)
v = array([ -4, 3, 9, 7 ],float)

# solve uses a package of solvers (whatever is best)
x= solve(A,v)
print(x)

[ 2. -1. -2.  1.]
